# Generated by Django 6.0.3 on 2026-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfield',
            name='premiumtag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
