# Generated by Django 6.0.2 on 2026-02-20 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfield',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
