# Generated by Django 6.0.2 on 2026-03-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classfields', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='classfields.classfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.userclassfield')),
            ],
        ),
    ]
