# Generated by Django 6.0.2 on 2026-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclassfield',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user-avatars/'),
        ),
        migrations.AlterField(
            model_name='userclassfield',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
